import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { resolveRuntimeLayout } from "@queqiao/platform-paths";
import { createGatewayApp } from "./app.js";
import { loadGatewayConfigFile } from "./config.js";
import { listenGateway } from "./listen.js";
import { WorkerMembershipStore } from "./worker-membership-store.js";
import { MembershipWorkerRegistry } from "./worker-membership-registry.js";
import { EnrollmentService } from "./enrollment-service.js";
import { ensureGatewayManagementSecret } from "./management-secret.js";
import { createGatewayManagementApp } from "./management-app.js";
import { gatewayOperationsDiagnostics } from "./operations.js";

const layout = resolveRuntimeLayout();
const config = loadGatewayConfigFile(process.env.QUEQIAO_CONFIG_FILE || layout.configFile);
const memberships = new WorkerMembershipStore(config.stateDir);
const workerSource = new MembershipWorkerRegistry(memberships);
const enrollment = new EnrollmentService(memberships, config.stateDir);
const managementSecret = await ensureGatewayManagementSecret(config.stateDir);
const operations = gatewayOperationsDiagnostics(config.extensions);
const app = await createGatewayApp(config, enrollment, workerSource);
const host = config.host ?? "127.0.0.1";
listenGateway(app, config, () => { console.log(`Queqiao Gateway listening on http://${host}:${config.port}`); console.log(`Public MCP URL: ${config.resourceUrl}`); });
const packagedDashboard = fileURLToPath(new URL("./dashboard/", import.meta.url));
const developmentDashboard = path.resolve(process.cwd(), "dist/dashboard");
const dashboardDirectory = existsSync(packagedDashboard) ? packagedDashboard : existsSync(developmentDashboard) ? developmentDashboard : undefined;
const managementApp = createGatewayManagementApp({ secret: managementSecret.secret, enrollment, memberships, workers: workerSource, stateDirectory: config.stateDir, operations, ...(dashboardDirectory ? { dashboardDirectory } : {}) });
managementApp.listen(config.managementPort, "127.0.0.1", () => { console.log(`Queqiao Gateway management listening on http://127.0.0.1:${config.managementPort}`); if (dashboardDirectory) console.log(`Local Operations Dashboard: http://127.0.0.1:${config.managementPort}/dashboard/`); });
